FOOTBALL_DATA_KEY = ''
FOOTBALL_API_KEY = ''
CROWD_SCORE_KEY = ''  # Premier League is db id =2

# Twitter CONFIG
TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''
TWITTER_ACCESS_TOKEN = ''
TWITTER_ACCESS_SECRET = ''

# DEBUG?
DEBUG = False
